config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :walkers do
    resources :reviews
  end
  root "walkers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :walkers
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :walker
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :walkers
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/walker.rb
class Walker < ApplicationRecord
  belongs_to :user
  belongs_to :area
  has_many :reviews

  validates_associated :user
  validates_associated :area
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :phone, numericality: { only_integer: true }
  validates :phone, length: { is: 10 }
  validates_format_of :phone, :with => /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/, :multiline => true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :city, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_walker
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.walker_id = @walker.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to walker_path(@walker)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to walker_path(@walker)
    else
      render "edit"
    end
  end

  def destroy
    @review.destroy
    redirect_to walker_path(@walker)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_walker
    @walker = Walker.find(params[:walker_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/controllers/walkers_controller.rb
class WalkersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :find_walker, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:area].blank?
      @walkers = Walker.all.order("created_at DESC")
    else
      @area_id = Area.find_by(name: params[:area]).id
      @walkers = Walker.where(:area_id => @area_id).order("created_at DESC")
    end

    # if @walker.reviews.blank?
    #   @average_review = 0
    # else
    #   @average_review = @walker.reviews.average(:rating).round(2)
    # end
  end

  def show
    if @walker.reviews.blank?
      @average_review = 0
    else
      @average_review = @walker.reviews.average(:rating).round(2)
    end
  end

  def new
    @walker = current_user.walkers.build
    @areas = Area.all.map { |a| [a.name, a.id] }
  end

  def create
    @walker = current_user.walkers.build(walker_params)
    @walker.area_id = params[:area_id]
    if @walker.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @areas = Area.all.map { |a| [a.name, a.id] }
  end

  def update
    @walker.area_id = params[:area_id]
    if @walker.update(walker_params)
      redirect_to walker_path(@walker)
    else
      render "edit"
    end
  end

  def destroy
    @walker.destroy
    redirect_to root_path
  end

  private

  def walker_params
    params.require(:walker).permit(:first_name, :last_name, :phone, :email, :city, :details, :area_id)
  end

  def find_walker
    @walker = Walker.find(params[:id])
  end

  def catch_not_found(e)
    Rails.logger.debug("We had a not found exception.")
    flash.alert = e.to_s
    redirect_to walkers_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/walkers_helper.rb
module WalkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wag the Dog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="/assets/jquery.raty.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-dark bg-dark">
        <div class="nav navbar-header">
          <%= link_to "Wag the Dog", root_path, class: "navbar-brand nav-item nav-link" %>
          <% if user_signed_in? %>
            <% if current_user.walkers.length === 0 %>
              <li class="nav-item nav-link"><%= link_to "Post Services", new_walker_path %></li>
            <% end %>
          <% end %>
        </div>
        <ul class="nav">
          <% if user_signed_in? %>
            <li class="nav-item nav-link"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class="nav-item nav-link"><%= link_to "Sign Up", new_user_registration_path %></li>
            <li class="nav-item nav-link"><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<h1>New Review</h1>

<%= simple_form_for([@walker, @walker.reviews.build]) do |f| %>
<div id="rating-form">
  <label for="">Rating </label>
</div>
  <%= f.input :comment %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

<script>
$('#rating-form').raty({
  path: '/assets/',
  scoreName: 'review[rating]'
});
</script>

app/views/reviews/_review.html.erb
<div class="review-card">
  <div class="review-rating" data-score="<%= review.rating %>">
  </div>
  <p>
    <%=review.comment%>
  </p>
  <div>
    <%= time_ago_in_words(review.created_at) %>
    <span> ago</span>
  </div>
  <div>
    <% if user_signed_in? %>
      <% if current_user.id == review.user_id%>
        <%= link_to "Edit", edit_walker_review_path(review.walker, review) %>
        <%= link_to "Delete", walker_review_path(review.walker, review), method: :delete, data: { confirm: "Are you sure?" } %>
      <% end%>
    <% end%>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<% if current_user.id == @review.user_id %>
<%= simple_form_for([@walker, @review]) do |f| %>
<div id="rating-form">
  <label for="">Rating </label>
</div>
  <%= f.input :comment %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>
<% else %>
<h1 class="lead">Sorry, you cannot other users reviews.</h1>
<% end %>

<script>
$('#rating-form').raty({
  path: '/assets/',
  scoreName: 'review[rating]'
});
</script>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/walkers/_form.html.erb
<%= simple_form_for @walker, :html => { :multipart => true } do |f| %>
  <%= select_tag(:area_id, options_for_select(@areas), :prompt => "Select an area") %>
  <%= f.input :first_name, label: "First Name" %>
  <%= f.input :last_name, label: "Last Name" %>
  <%= f.input :phone %>
  <%= f.input :email %>
  <%= f.input :city %>
  <%= f.input :details %>
  <%= f.submit "Submit", class: "btn-primary" %>
<% end%>

app/views/walkers/edit.html.erb
<h1>Edit Service Profile</h1>
<% if current_user.id != @walker.user_id %>
<h1 class="lead">Sorry, you cannot other users profiles.</h1>
<% else %>
<%= simple_form_for @walker, :html => { :multipart => true } do |f| %>
  <%= f.select :area_id, @areas %>
  <%= f.input :first_name, label: "First Name" %>
  <%= f.input :last_name, label: "Last Name" %>
  <%= f.input :phone %>
  <%= f.input :email %>
  <%= f.input :city %>
  <%= f.input :details %>
  <%= f.submit "Submit", class: "btn-primary" %>
<% end %>
<% end %>

app/views/walkers/index.html.erb
<p class="lead text-center">Connect to a dog walker in your area...
  <p>
    <nav class="nav navbar-nav mb-3">
      <ul class="nav justify-content-center nav-tabs">
        <% Area.all.each do |area| %>
          <li class="nav-item mx-2">
            <% if params[:area] == area.name %>
              <%= link_to area.name, walkers_path(area: area.name), class: "nav-link active p-2" %>
            <% else %>
              <%= link_to area.name, walkers_path(area: area.name), class: "link nav-link p-2" %>
            <% end%>
          </li>
        <% end %>
      </ul>
    </nav>
    <% if @walkers.count == 0 %>
      <h1 class="lead text-center mt-5">Sorry, there are currently no dog walkers registered for this area.</h1>
    <% end %>
    <% random = 1 %>
    <% @walkers.each do |walker| %>
      <%if walker.reviews.blank?%>
        <%average_review = 0%>
      <% else %>
        <% average_review = walker.reviews.average(:rating).round(2) %>
      <% end %>
      <div class="card mb-3" style="max-width: 650px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="https://picsum.photos/200?random=<%= random %>" class="img-fluid rounded-start" alt="profile-image">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">
                <span><%= link_to walker.first_name + " " + walker.last_name, walker_path(walker) %></span>
              </h5>
              <p class="card-text"><%= walker.city %></p>
              <div>
                <% if walker.reviews.count == 0 %>
                  <span>This user has no reviews yet.</span>
                <% else %>
                  <span class="average-review-rating" data-score="<%= average_review %>"></span>
                  <span>(<%= walker.reviews.count  %>)</span>
                <% end %>
              </div>
              <p class="card-text"><small class="text-muted">Last updated <%= time_ago_in_words(walker.created_at) %> ago</small></p>
            </div>
          </div>
        </div>
      </div>
      <% random = random + 1 %>
    <% end %>
    <script>
      $('.average-review-rating').raty({
        readOnly: true,
          path: '/assets/',
        score: function() {
          return $(this).attr('data-score');
        },
      });
    </script>

app/views/walkers/new.html.erb
<h1>Post Services</h1>

<%= render 'form' %>

app/views/walkers/show.html.erb
<div class="d-flex justify-content-between align-items-end mb-3 show-layout">
  <div class="flex-item">
    <img src="https://picsum.photos/300" alt="">
  </div>
  <div class="contact-info">
    <h1><%= @walker.first_name + " " + @walker.last_name %></h1>
    <div>
      <span class="average-review-rating"data-score="<%=  @average_review %>">
      </span>
      <span>(<%= @walker.reviews.count %>)</span>
    </div>
    <br/>
    <h2><%= @walker.area.name + " - " + @walker.city %></h2>
    <h3><%= @walker.phone %></h3>
    <h3><%= @walker.email %></h3>
  </div>
</div>
<div class="d-flex justify-content-between show-bottom">
  <div class="reviews">
    <%= render @walker.reviews.order("created_at DESC") %>
  </div>
  <div class="details">
    <p><%= @walker.details %></p>
  </div>
</div>
<div class="text-center">
  <%= link_to "Back",  walkers_path %>
  <% if user_signed_in? %>
    <% if current_user.id === @walker.user_id %>
      <%= link_to 'Edit', edit_walker_path %>
      <%= link_to 'Delete', walker_path(@walker), method: :delete, data: { confirm: "Are you sure? "} %>
    <% else %>
      <%= link_to "Write a review", new_walker_review_path(@walker) %>
    <% end %>
  <% end %>
</div>
<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>
<script>
  $('.average-review-rating').raty({
    readOnly: true,
      path: '/assets/',
    score: function() {
      return $(this).attr('data-score');
    },
  });
</script>